# Generated by Django 4.0.5 on 2022-07-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_rename_notifications_type_notifications_notification_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='notification_types',
            field=models.CharField(choices=[('Blog', 'Blog'), ('Like', 'Like'), ('Follow', 'Follow'), ('Comment', 'Comment'), ('Reply', 'Reply')], max_length=20),
        ),
    ]
