# Generated by Django 4.0.5 on 2022-07-04 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_follow_user_followers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='followedby',
            new_name='followed_by',
        ),
    ]
